language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.32.0

before_script:
  rustup component add rustfmt --toolchain nightly

script:
  - cargo +nightly fmt --all -- --check
  - cargo build --verbose
  - cargo test --verbose
