# Log level option used to set RUST_LOG for the rust env logger
log_level = "coordinator"

# Duration that we wait for challenge responses from guardnodes, in seconds
challenge_duration = 60

# Duration that we attempt to verify a challenge transaction before skipping, in seconds
verify_duration = 150

# Host address that the listener binds to and receives guardnode requests
listener_host = "localhost:9999"

[clientchain]
host = "http://127.0.0.1:5555"
user = "user1"
pass = "password1"
asset = "CHALLENGE"
asset_hash = "73be00507b15f79efccd0184b7ca8367372dfd5334ae8991a492f5f354073c88"
genesis_hash = "73902d2a365fff2724e26d975148124268ec6a84991016683817ea2c973b199b"
