#!/bin/bash

CARGO_FMT="cargo +nightly fmt"

$CARGO_FMT --version &>/dev/null
if [ $? != 0 ]; then
    printf "[pre_commit] \033[0;31merror\033[0m: \"$CARGO_FMT\" not available?\n"
    exit 1
fi

$CARGO_FMT -- --check
if [ $? != 0 ]; then
    printf "[pre_commit] $CARGO_FMT → \033[0;31merror\033[0m \n"
else
    printf "[pre_commit] $CARGO_FMT → \033[0;32mOK\033[0m \n"
fi
